### ISSUE TITLE
Test 1

### ISSUE THREAD

**Issue by shams-ahmed** [myfitsapp/plugin#1]
Create new endpoint:

where the client can send a list of clothes-> Backend will send all the list back

Hon - Currently looking at this

**Comment by shams-ahmed** [comment]
@mashtheweb take a look at this first

**Comment by shams-ahmed** [comment]
i looked at Assets, seem like there very litter implementation done on the SDK

**Comment by mashtheweb** [comment]
Added end point to add items to a named collection by passing name collection name, description, and the user name.
